services:
  laravel.test:
    build:
      context: './docker'
      dockerfile: Dockerfile
      args:
        WWWGROUP: '${WWWGROUP}'
    image: 'sail-8.3/app'
    container_name: laravel-app
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    ports:
      - '${VITE_PORT:-5173}:${VITE_PORT:-5173}'  # Puerto para Vite si lo usas
    environment:
        WWWUSER: '${WWWUSER}'
        LARAVEL_SAIL: 1
        XDEBUG_MODE: '${SAIL_XDEBUG_MODE:-off}'
        XDEBUG_CONFIG: '${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}'
        IGNITION_LOCAL_SITES_PATH: '${PWD}'
    volumes:
      - '.:/var/www/html'
    networks:
      - sail
    depends_on:
      - db

  db:
      container_name: laravel-mysql
      image: 'mariadb:10.6'
      ports:
          - '${FORWARD_DB_PORT:-3306}:3306'
      environment:
          MARIADB_DATABASE: '${DB_DATABASE}'
          MARIADB_USER: '${DB_USERNAME}'
          MARIADB_PASSWORD: '${DB_PASSWORD}'
          MARIADB_ROOT_PASSWORD: '${DB_PASSWORD}'
      volumes:
          - 'sail-mysql:/var/lib/mysql'
          - './basededatos.sql:/docker-entrypoint-initdb.d/basededatos.sql'
      networks:
          - sail
      healthcheck:
          test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
          interval: 10s
          timeout: 5s
          retries: 3

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - 8000:80
    environment:
      PMA_HOST: db
      MYSQL_USER: user
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: 1234
  nginx:
    build:
      context: ./nginx
    container_name: laravel-nginx
    ports:
      - "80:80"
    volumes:
      - '.:/var/www/html'
    depends_on:
      - laravel.test
    restart: always
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local